apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "objectstorage.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "objectstorage.labels" . | nindent 4 }}
data:
  config.yaml: |-
    cloud:
      domain: {{ default .Values.objectstorageConfig.cloudDomain .Values.cloudDomain | quote }}
      {{- if eq (include "objectstorage.scheme" .) "http" }}
      port: {{ default 80 (default .Values.objectstorageConfig.httpPort .Values.httpPort) }}
      {{- else }}
      port: {{ default 443 (default .Values.objectstorageConfig.cloudPort .Values.cloudPort) }}
      {{- end }}
    objectStorage:
      resources:
        hostingPodCpuMilliCores: {{ .Values.objectstorageConfig.hostingPodCpuMilliCores }}
        hostingPodMemoryMiB: {{ .Values.objectstorageConfig.hostingPodMemoryMiB }}
      components:
        monitoring:
          url: {{ include "objectstorage.monitorUrl" . | quote }}
        billing:
          url: {{ .Values.objectstorageConfig.billingUrl | quote }}
          secret: {{ .Values.objectstorageConfig.billingSecret | quote }}
        appLaunchpad:
          url: {{ .Values.objectstorageConfig.appLaunchpadUrl | quote }}
        objectStorage:
          internalEndpoint: {{ include "objectstorage.objectStorageEndpoint" . | quote }}
          externalEndpoint: {{ include "objectstorage.apiHost" . | quote }}
      realName:
        appTokenJwtKey: {{ .Values.objectstorageConfig.appTokenJwtKey | quote }}
      hosting:
        appNamePrefix: {{ .Values.objectstorageConfig.hostingAppNamePrefix | quote }}
        networkProtocol: {{ .Values.objectstorageConfig.hostingNetworkProtocol | quote }}
        networkPort: {{ .Values.objectstorageConfig.hostingNetworkPort }}
