apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectstorage-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "objectstorage.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    control-plane: controller-manager
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "objectstorage.labels" . | nindent 8 }}
        app.kubernetes.io/component: controller
        control-plane: controller-manager
    spec:
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      affinity:
        {{- toYaml .Values.controller.affinity | nindent 8 }}
      containers:
        - name: manager
          image: {{ .Values.controller.image | quote }}
          imagePullPolicy: {{ .Values.controller.imagePullPolicy }}
          command:
            - /manager
          args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --monitor-bind-address=:{{ .Values.controller.monitor.port }}
            - --leader-elect
          env:
            - name: OSNamespace
              valueFrom:
                configMapKeyRef:
                  name: {{ include "objectstorage.fullname" . }}-config
                  key: OSNamespace
            - name: OSAdminNamespace
              valueFrom:
                configMapKeyRef:
                  name: {{ include "objectstorage.fullname" . }}-config
                  key: OSAdminNamespace
            - name: OSAdminSecret
              valueFrom:
                configMapKeyRef:
                  name: {{ include "objectstorage.fullname" . }}-config
                  key: OSAdminSecret
            - name: OSInternalEndpoint
              valueFrom:
                configMapKeyRef:
                  name: {{ include "objectstorage.fullname" . }}-config
                  key: OSInternalEndpoint
            - name: OSExternalEndpoint
              valueFrom:
                configMapKeyRef:
                  name: {{ include "objectstorage.fullname" . }}-config
                  key: OSExternalEndpoint
            - name: OSUDetectionCycleSeconds
              valueFrom:
                configMapKeyRef:
                  name: {{ include "objectstorage.fullname" . }}-config
                  key: OSUDetectionCycleSeconds
            - name: OSBDetectionCycleSeconds
              valueFrom:
                configMapKeyRef:
                  name: {{ include "objectstorage.fullname" . }}-config
                  key: OSBDetectionCycleSeconds
            - name: OBJECT_STORAGE_INSTANCE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "objectstorage.fullname" . }}-config
                  key: OBJECT_STORAGE_INSTANCE
            - name: PROMETHEUS_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "objectstorage.fullname" . }}-config
                  key: PROMETHEUS_SERVICE_HOST
          ports:
            - name: monitor
              containerPort: {{ .Values.controller.monitor.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
      serviceAccountName: objectstorage-controller-manager
      terminationGracePeriodSeconds: 10
