apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "objectstorage.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "objectstorage.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      {{- include "objectstorage.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        {{- include "objectstorage.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.frontend.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.frontend.image | quote }}
          imagePullPolicy: {{ .Values.frontend.imagePullPolicy }}
          {{- if .Values.frontend.securityContext }}
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          env:
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: {{ .Values.platform.tlsRejectUnauthorized | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          volumeMounts:
            - name: object-storage-frontend-volume
              mountPath: /app/data/config.yaml
              subPath: config.yaml
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: object-storage-frontend-volume
          configMap:
            name: {{ include "objectstorage.fullname" . }}-config
