apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "objectstorage.labels" . | nindent 4 }}
  name: {{ include "objectstorage.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      protocol: TCP
      targetPort: {{ .Values.frontend.service.port }}
  selector:
    {{- include "objectstorage.selectorLabels" . | nindent 4 }}
