frontend:
  image: ghcr.io/labring/sealos-objectstorage-frontend:latest
  imagePullPolicy: Always
  nameOverride: ""
  fullnameOverride: "object-storage-frontend"
  replicaCount: 1
  podAnnotations: {}
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1001
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - "ALL"
  service:
    port: 3000
  ingress:
    className: nginx
    host: ""
    annotations: {}
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 10m
      memory: 128Mi
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: "app"
                  operator: In
                  values:
                    - object-storage-frontend
            topologyKey: "kubernetes.io/hostname"

platform:
  tlsRejectUnauthorized: "1"

controller:
  image: ghcr.io/labring/sealos-objectstorage-controller:latest
  imagePullPolicy: Always
  replicaCount: 1
  monitor:
    port: 9090
    ingress:
      className: nginx
      annotations: {}
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 5m
      memory: 64Mi
  podSecurityContext:
    runAsNonRoot: true
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    capabilities:
      drop:
        - "ALL"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
                  - arm64
                  - ppc64le
                  - s390x
              - key: kubernetes.io/os
                operator: In
                values:
                  - linux
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: "control-plane"
                  operator: In
                  values:
                    - controller-manager
            topologyKey: "kubernetes.io/hostname"

objectstorageConfig:
  minio:
    namespace: ""
    externalHost: ""
  monitor:
    externalHost: ""
    prometheusUrl: "http://vmselect-victoria-metrics-k8s-stack.vm.svc:8481/select/0/prometheus/"
    prometheusToken: ""
  controller:
    userDetectionCycleSeconds: "300"
    bucketDetectionCycleSeconds: "300"
  billingUrl: ""
  billingSecret: ""
  appLaunchpadUrl: "http://applaunchpad-frontend.applaunchpad-frontend.svc.cluster.local:3000/api/v1alpha"
  renameEnable: false
  appTokenJwtKey: ""
  hostingPodCpuMilliCores: 200
  hostingPodMemoryMiB: 128
  hostingAppNamePrefix: "static-host"
  hostingNetworkProtocol: "HTTP"
  hostingNetworkPort: 80

cloudDomain: "127.0.0.1.nip.io"
cloudPort: ""
httpPort: ""
disableHttps: false
certSecretName: "wildcard-cert"
